#!/bin/bash
##################################################################################################
# 
# Copyright (C) 2018 Cloudera, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
##################################################################################################

# Include file: test-config
. ./test-config

rm -f test-files/*.ini
rm -f test-files/*.list

for group in ${hostgroups[@]}; 
do
  echo "Host Group: $group"; 
  
  eval hostsvar=( \${hosts_$group[@]} ) ;
  echo "  Hosts In Group: ${hostsvar[@]} (Saving to test-files/${group}.list)";
  rm -f test-files/${group}.list

  for host in ${hostsvar[@]};
  do
    echo ${host} >> test-files/${group}.list
  done

  eval dirsvar=( \${dirs_$group[@]} );
  echo "  Data Directories in Host Group: ${dirsvar[@]}"

done

for workload in ${general_workloads[@]};
do
  for worksize in ${general_worksizes[@]};
  do
    for group in ${hostgroups[@]}; 
    do
      eval target="test-files/${workload}_${worksize}_${group}.ini"
      eval header="fio-test-templates/blk-${worksize}.header"
      eval template="fio-test-templates/${workload}.template"
     
      sed "s#TESTTIME#${testtime}#g;s#OSQD#${osqd}#g" ${header} > $target
      
      eval dirsvar=( \${dirs_$group[@]} ) ;
      for dir in ${dirsvar[@]};
      do
        sed "s#DATADIR#${dir}#g;s#TESTDIR#${testdir}#g;s#LABEL#${dir//\//.}#g" $template >> $target
      done
    done
  done
done

for workload in ${master_workloads[@]};
do
  for worksize in ${master_worksizes[@]};
  do
    for group in ${hostgroups[@]}; 
    do
      eval grouptype=( \${type_${group}} )
      if [ "$grouptype" = "master" ]; then
        eval target="test-files/${workload}_${worksize}_${group}.ini"
        eval header="fio-test-templates/blk-${worksize}.header"
        eval template="fio-test-templates/${workload}.template"
      
        sed "s#TESTTIME#${testtime}#g;s#OSQD#${osqd}#g" ${header} > $target
        
        eval dirsvar=( \${dirs_$group[@]} ) ;
        for dir in ${dirsvar[@]};
        do
          sed "s#DATADIR#${dir}#g;s#TESTDIR#${testdir}#g;s#LABEL#${dir//\//.}#g" $template >> $target
        done
      fi;
    done
  done
done
