#!/bin/bash
##################################################################################################
# 
# Copyright (C) 2018 Cloudera, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
##################################################################################################

defhostlistfile="host.list"
defcommand="echo Your command goes here"

hostlistfile=${1:-$defhostlistfile}
command=${2:-$defcommand}

echo "Running ($command) on hosts from $hostlistfile"

while read REMOTE_SERVER
do
        ssh -n -tt $REMOTE_SERVER "$command" &
done < $hostlistfile
sleep 2
wait
echo "Completed on all hosts in $hostlistfile"
